import {
  pgTable,
  uuid,
  varchar,
  doublePrecision,
  timestamp,
  integer,
} from "drizzle-orm/pg-core";

export const backtestRapidDropRuns = pgTable("backtest_rapid_drop_runs", {
  id: uuid("id").primaryKey().defaultRandom(),
  symbol: varchar("symbol", { length: 20 }).notNull(),
  fromTime: timestamp("from_time", { withTimezone: true }).notNull(),
  toTime: timestamp("to_time", { withTimezone: true }).notNull(),
  windowSeconds: integer("window_seconds").notNull(),
  dropPercent: doublePrecision("drop_percent").notNull(),
  recordAfterSeconds: integer("record_after_seconds").notNull(),
  cooldownSeconds: integer("cooldown_seconds").notNull(),
  eventsFound: integer("events_found").notNull().default(0),
  avgDrawdownAfterBuy: doublePrecision("avg_drawdown_after_buy"),
  avgRecovery1min: doublePrecision("avg_recovery_1min"),
  avgRecovery2min: doublePrecision("avg_recovery_2min"),
  avgRecovery5min: doublePrecision("avg_recovery_5min"),
  avgRecovery10min: doublePrecision("avg_recovery_10min"),
  winRate1min: doublePrecision("win_rate_1min"),
  winRate2min: doublePrecision("win_rate_2min"),
  winRate5min: doublePrecision("win_rate_5min"),
  winRate10min: doublePrecision("win_rate_10min"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
